commander/app.py, tests/test_commands.py
Returns code 400 if wrong json data.
Returns code 504 if timeout on cmd.start .
=> Error responses

Dockerfile, Dockerfile-dev, commander/start-daemon-dev.sh, commander/start-daemon.sh
=> Update base image to b101

.env, Dockerfile-deploy, commander/commands.py, commander/start-daemon.sh, docker-compose.yml
Make build cycle a variable in a .env file.
Patch remotes so they look as being from a CSC.
Add dockerfile to build commander with deployment image.
=> Minor improvements in `commands.py`.

commander/start-daemon-dev.sh
Builds LOVE CSC idl files on entrypoint
=> Xml version fix

commander/app.py, commander/commands.py, tests/conftest.py, tests/test_commands.py, tests/test_lovecsc.py, tests/test_salinfo.py
This PR fixes some errors related to asyncio library. Some tests started failing after a salobj library update, so minor fixes were done to maintain compatibility
=> Fix tests runtime error

commander/lovecsc.py, commander/salinfo.py
This PR apply linter fixes to every code in the repository.
=> Black formatter fixes

commander/efd.py
This PR remove except specification to catch all possible exceptions when trying to connect to the EFD.
=> Hotfix efdclient

Jenkinsfile
This PR adds tickets branch for docker images build and push steps
=> Build docker images from tickets branch

.env, Jenkinsfile, docker-compose.yml
A new development environment was released, so this PR updates the image and make some adjustments to comply with the new version.
=> Upgrade to lsstts/develop-env:c0018.000

.env, .flake8, Jenkinsfile, commander/app.py, commander/commands.py, commander/efd.py, commander/heartbeats.py, commander/lovecsc.py, commander/salinfo.py, commander_utils.py, tests/conftest.py, tests/test_commands.py, tests/test_efd.py, tests/test_heartbeats.py, tests/test_lovecsc.py, tests/test_salinfo.py
This PR make some changes to be compliant with the `develop-env` version `c0018.001`.
=> Upgrade develop-env to c0018.001

Dockerfile
This PR is a hotfix that reverts a previous change to the `Dockerfile`
=> Rollback to previous change

commander/tcs.py
After a recent update (https://jira.lsstcorp.org/browse/LOVE-27) the LOVE-commander stopped working, this PR solves the issue
=> LOVE-commander of linode environment stopped working after recent update

setup.py
Minor fix to setup.py. For some reason I committed the wrong version of the file.
=> DM-30455: Fix conda recipe in LOVE-commander

.env, Jenkinsfile
This PR update .env file of the local live environments, changing dev_cycle from `c0020.001` to `c0020.006`
=> Upgrade dev-cycle to c0020.006

commander/lovecsc.py
This PR refactors the observing log endpoint to fix an issue that prevented the LOVE CSC to be connected
=> Refactor Observing Logs endpoint

commander/efd.py
This PR refactors the EFD endpoint to be able to configure different efd instances, also a new method was added to list these efd instances
=> Refactor EFD Enpoint

Jenkinsfile, commander/app.py, commander/efd.py, commander/lovecsc.py, commander/tcs.py, commander_utils.py, docker/docker-compose.yml, tests/test_commands.py, tests/test_efd.py, tests/test_lovecsc.py, tests/test_salinfo.py
This PR uncomments the EFD API which was first commented as it was on maintenance. This changes reactivates it to allow querying different EFD instances.
=> Fix problems with EFD querying

commander/efd.py, tests/test_efd.py, tests/test_tcs.py
This PR adds an improvement feature that will allow the EventLog component to query the EFD. A new commander endpoint was added.
=> Add EFD logMessage endpoint

commander/lovecsc.py
This PR updates a deprecated method as Salobj 7 was released.
=> Change deprecated event.put method

.github/workflows/changelog.yml, CHANGELOG.rst
This PR adds configuration for the [Changelog checker](https://github.com/marketplace/actions/changelog-checker) github action.
=> Add changelog checker
